package hex.core;

/**
 * ...
 * @author Francis Bourre
 */
enum ApplicationAssemblerMessage
{
	CONTEXT_PARSED;
	ASSEMBLING_START;
	STATE_TRANSITIONS_BUILT;
	OBJECTS_BUILT;
	METHODS_CALLED;
	DOMAIN_LISTENERS_ASSIGNED;
	MODULES_INITIALIZED;
	ASSEMBLING_END;
}